//HintName: Solution.g.cs
// <auto-generated/>

using Microsoft.VisualStudio.SolutionPersistence.Model;
using Fuke.Common.ProjectModel;
using Fuke.Common.IO;
using System.Runtime.CompilerServices;

internal class Solution(SolutionModel model, AbsolutePath path) : Fuke.Common.ProjectModel.Solution(model, path)
{
    public Fuke.Common.ProjectModel.Project _build => this.GetProject("_build");
    public Fuke.Common.ProjectModel.Project Fuke_Build => this.GetProject("Fuke.Build");
    public Fuke.Common.ProjectModel.Project Fuke_Build_Shared => this.GetProject("Fuke.Build.Shared");
    public Fuke.Common.ProjectModel.Project Fuke_Build_Tests => this.GetProject("Fuke.Build.Tests");
    public Fuke.Common.ProjectModel.Project Fuke_Common => this.GetProject("Fuke.Common");
    public Fuke.Common.ProjectModel.Project Fuke_Common_Tests => this.GetProject("Fuke.Common.Tests");
    public Fuke.Common.ProjectModel.Project Fuke_Components => this.GetProject("Fuke.Components");
    public Fuke.Common.ProjectModel.Project Fuke_GlobalTool => this.GetProject("Fuke.GlobalTool");
    public Fuke.Common.ProjectModel.Project Fuke_GlobalTool_Tests => this.GetProject("Fuke.GlobalTool.Tests");
    public Fuke.Common.ProjectModel.Project Fuke_MSBuildTasks => this.GetProject("Fuke.MSBuildTasks");
    public Fuke.Common.ProjectModel.Project Fuke_ProjectModel => this.GetProject("Fuke.ProjectModel");
    public Fuke.Common.ProjectModel.Project Fuke_ProjectModel_Tests => this.GetProject("Fuke.ProjectModel.Tests");
    public Fuke.Common.ProjectModel.Project Fuke_SolutionModel => this.GetProject("Fuke.SolutionModel");
    public Fuke.Common.ProjectModel.Project Fuke_SolutionModel_Tests => this.GetProject("Fuke.SolutionModel.Tests");
    public Fuke.Common.ProjectModel.Project Fuke_SourceGenerators => this.GetProject("Fuke.SourceGenerators");
    public Fuke.Common.ProjectModel.Project Fuke_SourceGenerators_Tests => this.GetProject("Fuke.SourceGenerators.Tests");
    public Fuke.Common.ProjectModel.Project Fuke_Tooling => this.GetProject("Fuke.Tooling");
    public Fuke.Common.ProjectModel.Project Fuke_Tooling_Generator => this.GetProject("Fuke.Tooling.Generator");
    public Fuke.Common.ProjectModel.Project Fuke_Tooling_Tests => this.GetProject("Fuke.Tooling.Tests");
    public Fuke.Common.ProjectModel.Project Fuke_Utilities => this.GetProject("Fuke.Utilities");
    public Fuke.Common.ProjectModel.Project Fuke_Utilities_IO_Compression => this.GetProject("Fuke.Utilities.IO.Compression");
    public Fuke.Common.ProjectModel.Project Fuke_Utilities_IO_Globbing => this.GetProject("Fuke.Utilities.IO.Globbing");
    public Fuke.Common.ProjectModel.Project Fuke_Utilities_Net => this.GetProject("Fuke.Utilities.Net");
    public Fuke.Common.ProjectModel.Project Fuke_Utilities_Tests => this.GetProject("Fuke.Utilities.Tests");
    public Fuke.Common.ProjectModel.Project Fuke_Utilities_Text_Json => this.GetProject("Fuke.Utilities.Text.Json");
    public Fuke.Common.ProjectModel.Project Fuke_Utilities_Text_Yaml => this.GetProject("Fuke.Utilities.Text.Yaml");

    public _misc misc => Unsafe.As<_misc>(this.GetSolutionFolder("misc"));

    internal class _misc(SolutionFolderModel model, Fuke.Common.ProjectModel.Solution solution) : Fuke.Common.ProjectModel.SolutionFolder(model, solution)
    {


    }
}
